spring:
  data:
    mongodb:
      port: 27017
      database: mongoTestDB
      host: localhost
  main:
    allow-bean-definition-overriding: true

mongock:
  runner-type: initializingbean
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
