spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
application:
  numberOfCorrectAnswersToSuccessfullyPass: 4
  locale: ru_RU
  quizFileNameByLocaleTag:
    ru_RU: questions_ru.csv
    en_US: questions.csv
    en_EN: questions.csv